 /* 请先搜索是否有你的弹层模块，没有的话才添加 */

var modules = {
    "plugin/dialog/alert": require("./alert"),
    "plugin/dialog/confirm": require("./confirm"),
    "plugin/dialog/win": require("./win"),
    "plugin/dialog/dialog": require("./dialog"),
    "lib/layer/popup": require("lib/layer/popup"),
    "plugin/dialog/wait": require("./wait"),
    "plugin/dialog/toast": require("./toast"),
    "root/sales/adp/positionGroup/list/createDialog": require("root/sales/adp/positionGroup/list/createDialog"),
    "root/sales/adp/positionTemplate/list/createDialog": require("root/sales/adp/positionTemplate/list/createDialog"),
    "root/sales/adp/approve/createDialog": require("root/sales/adp/approve/createDialog"),
    "root/sales/adp/content/list/createCommonContentDialog": require("root/sales/adp/content/list/createCommonContentDialog"),
    "root/sales/marketing/list/createDialog": require("root/sales/marketing/list/createDialog"),
    "root/sales/marketing/list/actCinemasDialog": require("root/sales/marketing/list/actCinemasDialog"),
    "root/sales/marketing/list/recordsDialog": require("root/sales/marketing/list/recordsDialog"),
    "root/sales/marketing/list/confirmToSubmitDialog": require("root/sales/marketing/list/confirmToSubmitDialog"),
    "root/sales/marketing/list/protocolDialog": require("root/sales/marketing/list/protocolDialog"),
    "root/sales/naming/act/list/addDialog": require("root/sales/naming/act/list/addDialog"),
    "root/sales/naming/act/list/editDialog": require("root/sales/naming/act/list/editDialog"),
    "root/sales/naming/act/list/lookDialog": require("root/sales/naming/act/list/lookDialog"),
    "root/sales/naming/act/list/lookDetailDialog": require("root/sales/naming/act/list/lookDetailDialog"),
    "root/sales/naming/act/list/lookDetailDialogTip": require("root/sales/naming/act/list/lookDetailDialogTip"),
    "root/sales/naming/act/list/sendLogDialog": require("root/sales/naming/act/list/sendLogDialog"),
    "root/sales/naming/act/list/selectCinemaDialog": require("root/sales/naming/act/list/selectCinemaDialog"),
    "root/sales/marketing/list/creator": require("root/sales/marketing/list/creator"),
    "root/sales/marketing/baseInfo/addTimeDialog": require("root/sales/marketing/baseInfo/addTimeDialog"),
    "root/sales/marketing/conditionSetting/selectFilmDialog": require("root/sales/marketing/conditionSetting/selectFilmDialog"),
    "root/sales/marketing/conditionSetting/addTimeDialog": require("root/sales/marketing/conditionSetting/addTimeDialog"),
    "root/sales/marketing/conditionSetting/selectCinemaDialog": require("root/sales/marketing/conditionSetting/selectCinemaDialog"),
    "root/sales/marketing/priceAllocation/setBudgetDialog": require("root/sales/marketing/priceAllocation/setBudgetDialog"),
    "root/vip/mut/userTags/rule/createDialog": require("root/vip/mut/userTags/rule/createDialog"),
    "root/vip/mut/userTags/rule/lev1Dialog": require("root/vip/mut/userTags/rule/lev1Dialog"),
    "root/vip/mut/userTags/rule/lev2Dialog": require("root/vip/mut/userTags/rule/lev2Dialog"),
    "root/vip/mut/userTags/rule/lev3Dialog": require("root/vip/mut/userTags/rule/lev3Dialog"),
    "root/sales/adp/statReport/salesPlanStat/salesPlanStat/planPersonTop/planDetailDialog": require("root/sales/adp/statReport/salesPlanStat/salesPlanStat/planPersonTop/planDetailDialog"),
    "root/sales/adp/statReport/salesPlanStat/salesPlanStat/salesPlanTop/planDetailDialog": require("root/sales/adp/statReport/salesPlanStat/salesPlanStat/salesPlanTop/planDetailDialog"),
    "root/sales/adp/statReport/salesPlanStat/salesPlanStat/salesPlanTop/positionDialog": require("root/sales/adp/statReport/salesPlanStat/salesPlanStat/salesPlanTop/positionDialog"),
    "root/sales/adp/statReport/salesPlanStat/salesPlanStat/salesPlanOffLineTop/planDetailDialog": require("root/sales/adp/statReport/salesPlanStat/salesPlanStat/salesPlanOffLineTop/planDetailDialog"),
    "root/rmp/merchant/list/createDialog": require("root/rmp/merchant/list/createDialog"),
    "root/base/meta/cityGroup/createDialog": require("root/base/meta/cityGroup/createDialog"),
    "root/base/meta/accessTypeList/create": require("root/base/meta/accessTypeList/create"),
    "root/base/meta/showManage/cinemaShowList/createDialog": require("root/base/meta/showManage/cinemaShowList/createDialog"),
    "root/base/meta/showManage/cinemaShowList/syncDialog": require("root/base/meta/showManage/cinemaShowList/syncDialog"),
    "root/base/meta/showManage/cinemaShowList/detailDialog": require("root/base/meta/showManage/cinemaShowList/detailDialog"),
    "root/base/meta/showManage/cinemaShowList/lookFilm": require("root/base/meta/showManage/cinemaShowList/lookFilm"),
    "root/base/meta/showManage/cinemaShowList/failDialog": require("root/base/meta/showManage/cinemaShowList/failDialog"),
    "root/base/meta/showManage/cinemaShowList/errorDialog": require("root/base/meta/showManage/cinemaShowList/errorDialog"),
    "root/base/meta/showManage/channelShowList/detailDialog": require("root/base/meta/showManage/channelShowList/detailDialog"),
    "root/base/meta/showManage/channelShowList/lookFilm": require("root/base/meta/showManage/channelShowList/lookFilm"),
    "root/base/compasscbo/company/list/editDialog": require("root/base/compasscbo/company/list/editDialog"),
    "root/base/compasscbo/company/list/selectTabDialog": require("root/base/compasscbo/company/list/selectTabDialog"),
    "root/base/compasscbo/company/list/cinemasDetailDialog": require("root/base/compasscbo/company/list/cinemasDetailDialog"),
    "root/base/compasscbo/investment/list/editDialog": require("root/base/compasscbo/investment/list/editDialog"),
    "root/base/compasscbo/investment/list/selectTabDialog": require("root/base/compasscbo/investment/list/selectTabDialog"),
    "root/base/compasscbo/investment/list/cinemasDetailDialog": require("root/base/compasscbo/investment/list/cinemasDetailDialog"),
    "root/base/compasscbo/zoneprovince/list/zoneEditDialog": require("root/base/compasscbo/zoneprovince/list/zoneEditDialog"),
    "root/base/compasscbo/zoneprovince/list/zoneManageDialog": require("root/base/compasscbo/zoneprovince/list/zoneManageDialog"),
    "root/base/compasscbo/zoneprovince/list/provinceEditDialog": require("root/base/compasscbo/zoneprovince/list/provinceEditDialog"),
    "root/base/compasscbo/cinemahardware/list/editDialog": require("root/base/compasscbo/cinemahardware/list/editDialog"),
    "root/base/compasscbo/cinemalevelrule/list/addDialog": require("root/base/compasscbo/cinemalevelrule/list/addDialog"),
    "root/base/compasscbo/cinemalevelrule/list/cityManage": require("root/base/compasscbo/cinemalevelrule/list/cityManage"),
    "root/base/compasscbo/cinemalevelrule/list/ratioDialog": require("root/base/compasscbo/cinemalevelrule/list/ratioDialog"),
    "root/base/compasscbo/cinemalevelrule/list/editDialog": require("root/base/compasscbo/cinemalevelrule/list/editDialog"),
    "root/base/compasscbo/cinema/list/configDialog": require("root/base/compasscbo/cinema/list/configDialog"),
    "root/base/compasscbo/cinema/list/selectCompanyDialog": require("root/base/compasscbo/cinema/list/selectCompanyDialog"),
    "root/base/compasscbo/channelCinema/list/cinemaRelationDialog": require("root/base/compasscbo/channelCinema/list/cinemaRelationDialog"),
    "root/base/compasscbo/channelCinema/list/cinemaDetailDialog": require("root/base/compasscbo/channelCinema/list/cinemaDetailDialog"),
    "root/rmp/area/list/editContentDialog": require("root/rmp/area/list/editContentDialog"),
    "root/rmp/area/list/material": require("root/rmp/area/list/material"),
    "root/rmp/area/list/createDialog": require("root/rmp/area/list/createDialog"),
    "root/rmp/content/list/material": require("root/rmp/content/list/material"),
    "root/rmp/content/list/createDialog": require("root/rmp/content/list/createDialog"),
    "root/rmp/content/list/relateDevice": require("root/rmp/content/list/relateDevice"),
    "root/rmp/content/list/issuePosition": require("root/rmp/content/list/issuePosition"),
    "root/rmp/content/list/addDevice": require("root/rmp/content/list/addDevice"),
    "root/rmp/device/list/dialog": require("root/rmp/device/list/dialog"),
    "root/rmp/deviceCategory/getList/dialog": require("root/rmp/deviceCategory/getList/dialog"),
    "root/rmp/deviceType/getList/lookVersion": require("root/rmp/deviceType/getList/lookVersion"),
    "root/rmp/material/list/createDialog": require("root/rmp/material/list/createDialog"),
    "root/rmp/material/list/uploadDialog": require("root/rmp/material/list/uploadDialog"),
    "root/rmp/material/list/showImageDialog": require("root/rmp/material/list/showImageDialog"),
    "root/rmp/monitor/getList/addTicket": require("root/rmp/monitor/getList/addTicket"),
    "root/rmp/monitor/getList/addMaintain": require("root/rmp/monitor/getList/addMaintain"),
    "root/rmp/monitor/getSimList/createDialog": require("root/rmp/monitor/getSimList/createDialog"),
    "root/rmp/monitor/getSimList/payDialog": require("root/rmp/monitor/getSimList/payDialog"),
    "root/rmp/paperExpress/list/createDialog": require("root/rmp/paperExpress/list/createDialog"),
    "root/rmp/questionClass/list/createDialog": require("root/rmp/questionClass/list/createDialog"),
    "root/rmp/softVersion/getList/addDevice": require("root/rmp/softVersion/getList/addDevice"),
    "root/rmp/softVersion/getList/createDialog": require("root/rmp/softVersion/getList/createDialog"),
    "root/rmp/softVersion/getList/relateDevice": require("root/rmp/softVersion/getList/relateDevice"),
    "root/sales/act/act/act/list/createDialog": require("root/sales/act/act/act/list/createDialog"),
    "root/sales/act/act/act/list/configDialog": require("root/sales/act/act/act/list/configDialog"),
    "root/sales/act/act/act/list/detail": require("root/sales/act/act/act/list/detail"),
    "root/sales/act/act/act/list/editModule": require("root/sales/act/act/act/list/editModule"),
    "root/sales/act/act/act/list/sucDialog": require("root/sales/act/act/act/list/sucDialog"),
    "root/sales/act/base/blacklist/list/createDialog": require("root/sales/act/base/blacklist/list/createDialog"),
    "root/sales/act/base/blacklist/list/detailDialog": require("root/sales/act/base/blacklist/list/detailDialog"),
    "root/sales/act/prize/tipmobile/list/createDialog": require("root/sales/act/prize/tipmobile/list/createDialog"),
    "root/sales/adp/position/list/createDialog": require("root/sales/adp/position/list/createDialog"),
    "root/sales/adp/position/list/viewDialog": require("root/sales/adp/position/list/viewDialog"),
    "root/sales/adp/salesPlan/queryList/createDialog": require("root/sales/adp/salesPlan/queryList/createDialog"),
    "root/sales/adp/salesPlan/queryList/issueTypeDialog": require("root/sales/adp/salesPlan/queryList/issueTypeDialog"),
    "root/sales/adp/salesPlan/queryList/contentDialog": require("root/sales/adp/salesPlan/queryList/contentDialog"),
    "root/sales/adp/salesPlan/queryList/planDetailDialog": require("root/sales/adp/salesPlan/queryList/planDetailDialog"),
    "root/sales/adp/contentApprove/list/checkDialog": require("root/sales/adp/contentApprove/list/checkDialog"),
    "root/rmp/deviceType/getList/createDialog": require("root/rmp/deviceType/getList/createDialog"),
    "root/base/meta/film/lowPriceDialog": require("root/base/meta/film/lowPriceDialog"),
    "root/base/meta/film/lookDialog": require("root/base/meta/film/lookDialog"),
    "root/rmp/deviceState/list/sendout": require("root/rmp/deviceState/list/sendout"),
    "root/rmp/deviceState/list/install": require("root/rmp/deviceState/list/install"),
    "root/rmp/deviceState/list/polling": require("root/rmp/deviceState/list/polling"),
    "root/rmp/deviceState/list/add": require("root/rmp/deviceState/list/add"),
    "root/rmp/dailyWork/all/sendout": require("root/rmp/dailyWork/all/sendout"),
    "root/rmp/dailyWork/all/add": require("root/rmp/dailyWork/all/add"),
    "root/rmp/dailyWork/all/signin": require("root/rmp/dailyWork/all/signin"),
    "root/rmp/dailyWork/all/active": require("root/rmp/dailyWork/all/active"),
    "root/rmp/dailyWork/all/sendoutView": require("root/rmp/dailyWork/all/sendoutView"),
    "root/rmp/dailyWork/all/searchwork": require("root/rmp/dailyWork/all/searchwork"),
    "root/sales/adp/content/list/issuePosition": require("root/sales/adp/content/list/issuePosition"),
    "root/sales/adp/content/list/createCarouselDialog": require("root/sales/adp/content/list/createCarouselDialog"),
    "root/rmp/deviceState/list/searchwork": require("root/rmp/deviceState/list/searchwork"),
    "root/compass/datacompass/followExternalCinema/createDialog": require("root/compass/datacompass/followExternalCinema/createDialog"),
    "root/compass/datacompass/followExternalCinema/cinemaItemDialog": require("root/compass/datacompass/followExternalCinema/cinemaItemDialog"),
    "root/platform/ttAccount/queryPagination/licensee": require("root/platform/ttAccount/queryPagination/licensee"),
    "root/platform/ttAccount/queryPagination/createDialog": require("root/platform/ttAccount/queryPagination/createDialog"),
    "root/platform/ttAccount/queryPagination/theatersAuthorizationDialog": require("root/platform/ttAccount/queryPagination/theatersAuthorizationDialog"),
    "root/platform/ttAccount/queryPagination/cinemaGroupAuthorizationDialog": require("root/platform/ttAccount/queryPagination/cinemaGroupAuthorizationDialog"),
    "root/platform/ttAccount/queryPagination/selectCinemaDialog": require("root/platform/ttAccount/queryPagination/selectCinemaDialog"),
    "root/platform/ttAccount/queryPagination/roleAuthDialog": require("root/platform/ttAccount/queryPagination/roleAuthDialog"),
    "root/platform/pfAccount/queryPagination/roleAuthDialog": require("root/platform/pfAccount/queryPagination/roleAuthDialog"),
    "root/platform/pfAccount/queryPagination/licensee": require("root/platform/pfAccount/queryPagination/licensee"),
    "root/platform/pfAccount/queryPagination/createDialog": require("root/platform/pfAccount/queryPagination/createDialog"),
    "root/platform/tenant/queryPagination/empowerDialog": require("root/platform/tenant/queryPagination/empowerDialog"),
    "root/platform/tenant/queryPagination/createDialog": require("root/platform/tenant/queryPagination/createDialog"),
    "root/platform/tenant/queryPagination/configDialog": require("root/platform/tenant/queryPagination/configDialog"),
    "root/platform/tenant/queryPagination/tenantConfigurationDialog": require("root/platform/tenant/queryPagination/tenantConfigurationDialog"),
    "root/platform/role/platform/createDialog": require("root/platform/role/platform/createDialog"),
    "root/platform/role/platform/setRoleAuthDialog": require("root/platform/role/platform/setRoleAuthDialog"),
    "root/platform/role/tenant/createDialog": require("root/platform/role/tenant/createDialog"),
    "root/platform/role/tenant/setRoleAuthDialog": require("root/platform/role/tenant/setRoleAuthDialog"),
    "root/base/meta/parameterSet/paramDialog": require("root/base/meta/parameterSet/paramDialog"),
    "root/base/meta/channelList/relateDevice": require("root/base/meta/channelList/relateDevice"),
    "root/base/meta/channelList/blinkPage/createDialog": require("root/base/meta/channelList/blinkPage/createDialog"),
    "root/base/meta/parameterSet/addWarning": require("root/base/meta/parameterSet/addWarning"),
    "root/base/meta/film/timeDialog": require("root/base/meta/film/timeDialog"),
    "root/base/meta/film/cityListDialog": require("root/base/meta/film/cityListDialog"),
    "root/base/meta/film/lookLog": require("root/base/meta/film/lookLog"),
    "root/base/meta/cinemaLine/createDialog": require("root/base/meta/cinemaLine/createDialog"),
    "root/base/meta/cinemaList/createDialog": require("root/base/meta/cinemaList/createDialog"),
    "root/base/meta/filmContent/baseManage/createDialog": require("root/base/meta/filmContent/baseManage/createDialog"),
    "root/base/meta/filmContent/baseManage/uploadWin": require("root/base/meta/filmContent/baseManage/uploadWin"),
    "root/base/meta/filmContent/baseManage/lookSync": require("root/base/meta/filmContent/baseManage/lookSync"),
    "root/base/meta/filmContent/baseManage/Sync": require("root/base/meta/filmContent/baseManage/Sync"),
    "root/base/meta/filmContent/baseManage/syncInfo": require("root/base/meta/filmContent/baseManage/syncInfo"),
    "root/base/meta/filmContent/baseManage/batchSync": require("root/base/meta/filmContent/baseManage/batchSync"),
    "root/base/meta/cinemaList/cinemaSetDialog": require("root/base/meta/cinemaList/cinemaSetDialog"),
    "root/base/meta/cinemaList/lookDialog": require("root/base/meta/cinemaList/lookDialog"),
    "root/base/meta/film/deatilDialog": require("root/base/meta/film/deatilDialog"),
    "root/base/meta/cinemaList/areaDialog": require("root/base/meta/cinemaList/areaDialog"),
    "plugin/module/selectCinemaDialog": require("plugin/module/selectCinemaDialog"),
    "root/base/meta/filmContent/baseManage/picDialog": require("root/base/meta/filmContent/baseManage/picDialog"),
    "root/base/meta/filmContent/baseManage/addTeam": require("root/base/meta/filmContent/baseManage/addTeam"),
    "root/base/meta/filmContent/baseManage/bigPic": require("root/base/meta/filmContent/baseManage/bigPic"),
    "root/base/meta/filmContent/baseManage/inputDialog": require("root/base/meta/filmContent/baseManage/inputDialog"),
    "root/base/meta/filmContent/baseManage/lookChart": require("root/base/meta/filmContent/baseManage/lookChart"),
    "root/base/meta/filmContent/baseManage/syncFilm": require("root/base/meta/filmContent/baseManage/syncFilm"),
    "root/base/meta/filmContent/actorManage/createDialog": require("root/base/meta/filmContent/actorManage/createDialog"),
    "root/base/meta/filmContent/actorManage/uploadWin": require("root/base/meta/filmContent/actorManage/uploadWin"),
    "root/base/meta/filmContent/actorManage/picDialog": require("root/base/meta/filmContent/actorManage/picDialog"),
    "root/base/meta/filmContent/actorManage/lookStar": require("root/base/meta/filmContent/actorManage/lookStar"),
    "root/base/meta/filmContent/actorManage/bigPic": require("root/base/meta/filmContent/actorManage/bigPic"),
    "root/base/meta/filmContent/actorManage/syncActor": require("root/base/meta/filmContent/actorManage/syncActor"),
    "root/base/meta/filmContent/actorManage/inputDialog": require("root/base/meta/filmContent/actorManage/inputDialog"),
    "root/base/meta/filmContent/imageManage/createDialog": require("root/base/meta/filmContent/imageManage/createDialog"),
    "root/base/meta/filmContent/accessManage/createDialog": require("root/base/meta/filmContent/accessManage/createDialog"),
    "root/good/coupon/manage/createDialog": require("root/good/coupon/manage/createDialog"),
    "root/good/coupon/manage/selectFilmDialog": require("root/good/coupon/manage/selectFilmDialog"),
    "root/good/coupon/manage/selectCinemaDialog": require("root/good/coupon/manage/selectCinemaDialog"),
    "root/good/coupon/manage/selectHallDialog": require("root/good/coupon/manage/selectHallDialog"),
    "root/good/coupon/manage/selectDateDialog": require("root/good/coupon/manage/selectDateDialog"),
    "root/good/coupon/manage/addRuleDialog": require("root/good/coupon/manage/addRuleDialog"),
    "root/good/coupon/manage/viewDetailDialog": require("root/good/coupon/manage/viewDetailDialog"),
    "root/good/snak/snackType/createDialog": require("root/good/snak/snack/createDialog"),
    "root/good/snak/snackType/tabDialog": require("root/good/snak/snack/tabDialog"),
    "root/good/card/cardTypeManager/cardType/createDialog": require("root/good/card/cardTypeManager/cardType/createDialog"),
    "root/good/card/cardTypeManager/cardType/settingLevel": require("root/good/card/cardTypeManager/cardType/settingLevel"),
    "root/good/card/cardTypeManager/cardType/more": require("root/good/card/cardTypeManager/cardType/more"),
    "root/good/snak/cinemaSnack/channelDialog": require("root/good/snak/snackList/channelDialog"),
    "root/good/snak/cinemaSnack/createDialog": require("root/good/snak/snackList/createDialog"),
    "root/order/snakManage/snackOrder/lookbill": require("root/order/snakManage/snackOrder/lookbill"),
    "root/order/snackCusOrder/sendTicketNODialog": require("root/order/snackCusOrder/sendTicketNODialog"),
    "root/order/snackCusOrder/refundDialog": require("root/order/snackCusOrder/refundDialog"),
    "root/order/snackCusOrder/orderDetailDialog": require("root/order/snackCusOrder/orderDetailDialog"),
    "root/good/snak/cinemaSnack/lookGoodDialog": require("root/good/snak/snackList/lookGoodDialog"),
    "root/good/snak/cinemaSnack/detailDialog": require("root/good/snak/snackList/detailDialog"),
    "root/good/snak/cinemaSnack/putawayDialog": require("root/good/snak/snackList/putawayDialog"),
    "root/good/snak/cinemaSnack/addGoodDialog": require("root/good/snak/snackList/addGoodDialog"),
    "root/good/card/cardTypeManager/cardType/addType": require("root/good/card/cardTypeManager/cardType/addType"),
    "root/good/card/cardRuleApprove/ticketRule/createDialog2": require("root/good/card/cardRuleApprove/ticketRule/createDialog2"),
    "root/good/card/cardRuleApprove/ticketRule/createDialog": require("root/good/card/cardRuleApprove/ticketRule/createDialog"),
    "root/good/card/cardRuleApprove/ticketRule/createDialog3": require("root/good/card/cardRuleApprove/ticketRule/createDialog3"),
    "root/good/snackInfo/getSnackListByCinemaID/editPrice": require("root/good/snackInfo/getSnackListByCinemaID/editPrice"),
    "root/good/snackInfo/getSnackListByCinemaID/uploadDialog": require("root/good/snackInfo/getSnackListByCinemaID/uploadDialog"),
    "root/good/snackInfo/getSnackListByCinemaID/channelSet": require("root/good/snackInfo/getSnackListByCinemaID/channelSet"),
    "root/good/snackInfo/getSnackListByCinemaID/setLabel": require("root/good/snackInfo/getSnackListByCinemaID/setLabel"),
    "root/good/snackInfo/getSnackListByCinemaID/setType": require("root/good/snackInfo/getSnackListByCinemaID/setType"),
    "root/good/snackInfo/getSnackListByCinemaID/selectCinemaDialog": require("root/good/snackInfo/getSnackListByCinemaID/selectCinemaDialog"),
    "root/derivatives/good/batchManage/createDialog": require("root/derivatives/good/batchManage/createDialog"),
    "root/derivatives/good/batchManage/detailDialog": require("root/derivatives/good/batchManage/detailDialog"),
    "root/derivatives/good/batchManage/procureDialog": require("root/derivatives/good/batchManage/procureDialog"),
    "root/derivatives/good/batchManage/addProcureDialog": require("root/derivatives/good/batchManage/addProcureDialog"),
    "root/derivatives/good/batchManage/procureDetailDialog": require("root/derivatives/good/batchManage/procureDetailDialog"),
    "root/derivatives/goods/item/list/createDialog": require("root/derivatives/goods/item/list/createDialog"),
    "root/derivatives/goods/item/list/detailDialog": require("root/derivatives/goods/item/list/detailDialog"),
    "root/derivatives/goods/item/list/lossDialog": require("root/derivatives/goods/item/list/lossDialog"),
    "root/good/card/cardTypeManager/ticketRule/newDialog": require("root/good/card/cardTypeManager/ticketRule/newDialog"),
    "root/good/card/cardTypeManager/ticketRule/scheduleDialog": require("root/good/card/cardTypeManager/ticketRule/scheduleDialog"),
    "root/good/card/cardTypeManager/ticketRule/viewDetailDialog": require("root/good/card/cardTypeManager/ticketRule/viewDetailDialog"),
    "root/good/card/cardTypeManager/ticketRule/viewRuleDialog": require("root/good/card/cardTypeManager/ticketRule/viewRuleDialog"),
    "root/good/card/cardTypeManager/snackRule/newDialog": require("root/good/card/cardTypeManager/snackRule/newDialog"),
    "root/good/card/cardTypeManager/snackRule/viewDetailDialog": require("root/good/card/cardTypeManager/snackRule/viewDetailDialog"),
    "root/good/card/cardTypeManager/snackRule/viewRuleDialog": require("root/good/card/cardTypeManager/snackRule/viewRuleDialog"),
    "root/derivatives/cabinet/machine/list/add": require("root/derivatives/cabinet/machine/list/add"),
    "root/derivatives/cabinet/machine/deploy/add": require("root/derivatives/cabinet/machine/deploy/add"),
    "root/order/cardOrder/openCard/cardDetails": require("root/order/cardOrder/openCard/cardDetails"),
    "root/order/cardOrder/recharge/rechageOrder": require("root/order/cardOrder/recharge/rechageOrder"),
    "root/derivatives/goodsManage/product/list/look": require("root/derivatives/goodsManage/product/list/look"),
    "root/derivatives/adManage/adtop/list/createDialog": require("root/derivatives/adManage/adtop/list/createDialog"),
    "root/derivatives/adManage/category/list/createDialog": require("root/derivatives/adManage/category/list/createDialog"),
    "root/derivatives/adManage/category/list/detailDialog": require("root/derivatives/adManage/category/list/detailDialog"),
    "root/derivatives/adManage/rec/list/createDialog": require("root/derivatives/adManage/rec/list/createDialog"),
    "root/derivatives/goodsManage/group/list/addBasicInformation": require("root/derivatives/goodsManage/group/list/addBasicInformation"),
    "root/derivatives/goodsManage/group/list/configClass": require("root/derivatives/goodsManage/group/list/configClass"),
    "root/derivatives/goodsConfigure/flag/list/createDialog": require("root/derivatives/goodsConfigure/flag/list/createDialog"),
    "root/derivatives/goodsConfigure/flag/list/configDialog": require("root/derivatives/goodsConfigure/flag/list/configDialog"),
    "root/derivatives/goodsConfigure/code/list/createDialog1": require("root/derivatives/goodsConfigure/code/list/createDialog1"),
    "root/derivatives/goodsConfigure/code/list/configDialog": require("root/derivatives/goodsConfigure/code/list/configDialog"),
    "root/derivatives/goods/supplier/list/createDialog": require('root/derivatives/goods/supplier/list/createDialog'),
    "root/derivatives/goods/brand/list/createDialog": require("root/derivatives/goods/brand/list/createDialog"),
    "root/derivatives/good/batchManage/productDialog": require("root/derivatives/good/batchManage/productDialog"),
    "root/derivatives/goodsManage/group/list/lookDialog": require("root/derivatives/goodsManage/group/list/lookDialog"),
    "root/derivatives/adManage/ad/list/createDialog": require("root/derivatives/adManage/ad/list/createDialog"),
    "root/derivatives/base/channel/list/createDialog": require("root/derivatives/base/channel/list/createDialog"),
    "root/derivatives/base/channel/list/view": require("root/derivatives/base/channel/list/view"),
    "root/derivatives/base/cinema/list/createDialog": require("root/derivatives/base/cinema/list/createDialog"),
    "root/derivatives/base/film/list/createDialog": require("root/derivatives/base/film/list/createDialog"),
    "root/derivatives/base/film/list/Sync": require("root/derivatives/base/film/list/Sync"),
    "root/derivatives/base/expresscategory/list/createDialog": require("root/derivatives/base/expresscategory/list/createDialog"),
    "root/derivatives/base/invoicecategory/list/createDialog": require("root/derivatives/base/invoicecategory/list/createDialog"),
    "root/derivatives/base/enumclass/list/createDialog": require("root/derivatives/base/enumclass/list/createDialog"),
    "root/derivatives/base/enumclass/list/listDialog": require("root/derivatives/base/enumclass/list/listDialog"),
    "root/derivatives/base/enumclass/list/listManage": require("root/derivatives/base/enumclass/list/listManage"),
    "root/derivatives/base/apiclient/list/createDialog": require("root/derivatives/base/apiclient/list/createDialog"),
    "root/derivatives/base/config/list/createDialog": require("root/derivatives/base/config/list/createDialog"),
    "root/derivatives/adManage/rec/list/detailDialog": require("root/derivatives/adManage/rec/list/detailDialog"),
    "root/derivatives/goodsConfigure/category/list/createDialog": require("root/derivatives/goodsConfigure/category/list/createDialog"),
    "root/derivatives/goodsConfigure/category/list/configDialog": require("root/derivatives/goodsConfigure/category/list/configDialog"),
    "root/derivatives/goodsConfigure/attrcategory/list/createDialog1": require("root/derivatives/goodsConfigure/attrcategory/list/createDialog1"),
    "root/derivatives/goodsConfigure/attrcategory/list/createDialog2": require("root/derivatives/goodsConfigure/attrcategory/list/createDialog2"),
    "root/good/card/cardRuleApprove/snackRule/createDialog": require("root/good/card/cardRuleApprove/snackRule/createDialog"),
    "root/good/card/cardRuleApprove/snackRule/createDialog2": require("root/good/card/cardRuleApprove/snackRule/createDialog2"),
    "root/good/card/cardRuleApprove/snackRule/createDialog3": require("root/good/card/cardRuleApprove/snackRule/createDialog3"),
    "root/good/card/cardManager/cardDialog": require("root/good/card/cardManager/cardDialog"),
    "root/good/card/cardUser/scheduleDialog": require("root/good/card/cardUser/scheduleDialog"),
    "root/derivatives/goodsManage/group/list/previewFilm": require("root/derivatives/goodsManage/group/list/previewFilm"),
    "root/derivatives/order/order/list/complainDialog": require("root/derivatives/order/order/list/complainDialog"),
    "root/derivatives/order/order/list/barterDialog": require("root/derivatives/order/order/list/barterDialog"),
    "root/derivatives/order/order/list/detailDialog": require("root/derivatives/order/order/list/detailDialog"),
    "root/derivatives/goodsManage/product/edit/add": require("root/derivatives/goodsManage/product/edit/add"),
    "root/derivatives/goodsConfigure/attrcategory/list/editDialog": require("root/derivatives/goodsConfigure/attrcategory/list/editDialog"),
    "root/derivatives/order/order/list/applyDialog": require("root/derivatives/order/order/list/applyDialog"),
    "root/derivatives/order/order/list/setLossDialog": require("root/derivatives/order/order/list/setLossDialog"),
    "root/order/ticketOrderManager/list/orderDetailsDialog": require("root/order/ticketOrderManager/list/orderDetailsDialog"),
    "root/derivatives/order/order/list/deliverDialog": require("root/derivatives/order/order/list/deliverDialog"),
    "root/derivatives/goodsManage/product/manage/putaway": require("root/derivatives/goodsManage/product/manage/putaway"),
    "root/derivatives/goodsManage/product/manage/add": require("root/derivatives/goodsManage/product/manage/add"),
    "root/derivatives/goodsManage/product/manage/release": require("root/derivatives/goodsManage/product/manage/release"),
    "root/derivatives/goodsManage/product/manage/allot": require("root/derivatives/goodsManage/product/manage/allot"),
    "root/good/snak/snackGroup/createDialog": require("root/good/snak/snackType/createDialog"),
    "root/derivatives/goodsManage/group/list/addConfigure": require("root/derivatives/goodsManage/group/list/addConfigure"),
    "root/price/channel/approve/viewDialog": require("root/price/channel/approve/viewDialog"),
    "root/price/channel/audit/viewDialog": require("root/price/channel/audit/viewDialog"),
    "root/price/channel/policies/viewDialog": require("root/price/channel/policies/viewDialog"),
    "root/price/channel/policies/addFilmDialog": require("root/price/channel/policies/addFilmDialog"),
    "root/price/channel/policies/editPolicy/addRuleDialog": require("root/price/channel/policies/editPolicy/addRuleDialog"),
    "root/price/channel/policies/editPolicy/addChannelDialog": require("root/price/channel/policies/editPolicy/addChannelDialog"),
    "root/price/channel/policies/editPolicy/editChannelDialog": require("root/price/channel/policies/editPolicy/editChannelDialog"),
    "root/price/channel/policies/addTimeDialog": require("root/price/channel/policies/addTimeDialog"),
    "root/price/channel/policies/showTimeDialog": require("root/price/channel/policies/showTimeDialog"),
    "root/price/channel/policies/agreementDialog": require("root/price/channel/policies/agreementDialog"),
    "root/price/channel/policies/customConfirm": require("root/price/channel/policies/customConfirm"),
    "root/price/channel/policies/addCinemaDialog": require("root/price/channel/policies/addCinemaDialog"),
    "root/price/channel/policies/viewCinemaDialog": require("root/price/channel/policies/viewCinemaDialog"),
    "root/price/channel/rules/showTimeDialog": require("root/price/channel/rules/showTimeDialog"),
    "root/price/channel/rules/addCinemaDialog": require("root/price/channel/rules/addCinemaDialog"),
    "root/price/cinema/policies/editPolicy/addRuleDialog":require("root/price/cinema/policies/editPolicy/addRuleDialog"),
    "root/price/cinema/policies/addTimeDialog": require("root/price/cinema/policies/addTimeDialog"),
    "root/price/cinema/rules/showTimeDialog": require("root/price/cinema/rules/showTimeDialog"),
    "root/price/cinema/policies/showTimeDialog": require("root/price/cinema/policies/showTimeDialog"),
    "root/price/cinema/policies/agreementDialog": require("root/price/cinema/policies/agreementDialog"),
    "root/price/cinema/policies/customConfirm": require("root/price/cinema/policies/customConfirm"),
    "root/price/cinema/policies/viewDialog": require("root/price/cinema/policies/viewDialog"),
    "root/price/cinema/policies/viewCinemaDialog": require("root/price/cinema/policies/viewCinemaDialog"),
    "root/price/cinema/policies/addCinemaDialog": require("root/price/cinema/policies/addCinemaDialog"),
    "root/price/cinema/rules/addCinemaDialog": require("root/price/cinema/rules/addCinemaDialog"),
    "root/price/channel/policies/editTimeDialog": require("root/price/channel/policies/editTimeDialog"),
    "root/price/cinema/policies/editTimeDialog": require("root/price/cinema/policies/editTimeDialog"),
    "root/price/overview/viewDialog": require("root/price/overview/viewDialog"),
    "root/price/overview/viewExDialog": require("root/price/overview/viewExDialog"),
    "root/sales/act/act/act/list/add": require("root/sales/act/act/act/list/add"),
    "root/sales/act/act/act/list/config": require("root/sales/act/act/act/list/config"),
    "root/derivatives/goodsManage/group/list/config/addDialog": require("root/derivatives/goodsManage/group/list/config/addDialog"),
    "root/derivatives/goodsManage/group/list/config/choiceDialog": require("root/derivatives/goodsManage/group/list/config/choiceDialog"),
    "root/sales/act/stat/stat/list/userDialog": require("root/sales/act/stat/stat/list/userDialog"),
    "root/sales/act/stat/stat/list/recordDialog": require("root/sales/act/stat/stat/list/recordDialog"),
    "root/derivatives/goodsManage/product/manage/cinemaDialog": require("root/derivatives/goodsManage/product/manage/cinemaDialog"),
    "root/derivatives/goodsManage/group/list/config/lookDialog": require("root/derivatives/goodsManage/group/list/config/lookDialog"),
    "root/good/coupon/audit/createDialog": require("root/good/coupon/audit/createDialog"),"root/good/coupon/manage/exportDialog": require("root/good/coupon/manage/exportDialog"),
    "root/good/coupon/manage/exportCouponDialog": require("root/good/coupon/manage/exportCouponDialog"),
    "root/derivatives/goodsManage/group/list/config/purchaseDialog": require("root/derivatives/goodsManage/group/list/config/purchaseDialog"),
    "root/derivatives/goodsManage/group/list/config/editDialog": require("root/derivatives/goodsManage/group/list/config/editDialog"),
    "root/derivatives/goodsManage/group/list/editDialog": require("root/derivatives/goodsManage/group/list/editDialog"),
    "root/vip/mut/workbook/createDialog": require("root/vip/mut/workbook/createDialog"),
    "root/vip/mut/workbook/selectTabDialog": require("root/vip/mut/workbook/selectTabDialog"),
    "root/derivatives/goodsManage/product/listdel/lookDialog": require("root/derivatives/goodsManage/product/listdel/lookDialog"),
    "root/derivatives/goods/item/list/addLossDialog": require("root/derivatives/goods/item/list/addLossDialog"),
    "root/derivatives/goods/item/list/lossDetailDialog": require("root/derivatives/goods/item/list/lossDetailDialog"),
    "root/derivatives/adManage/adtop/config/createDialog": require("root/derivatives/adManage/adtop/config/createDialog"),
    "root/base/meta/film/abnormalDialog": require("root/base/meta/film/abnormalDialog"),
    "root/vip/mut/workbook/excludeDialog": require("root/vip/mut/workbook/excludeDialog"),
    "root/vip/report/selfRegisterReport/detailDialog": require("root/vip/report/selfRegisterReport/detailDialog"),
    "root/vip/report/distributeRegisterReport/detailDialog": require("root/vip/report/distributeRegisterReport/detailDialog"),
    "root/report/abnormalorder/abnormalOrderquery/verifyDialog": require("root/report/abnormalorder/abnormalOrderquery/verifyDialog"),
    "root/report/abnormalorder/abnormalOrderquery/verifyResultDialog": require("root/report/abnormalorder/abnormalOrderquery/verifyResultDialog"),
    "root/report/abnormalorder/abnormalOrderCauseManage/editDialog": require("root/report/abnormalorder/abnormalOrderCauseManage/editDialog"),
    "root/sales/act/stat/stat/list/winners": require("root/sales/act/stat/stat/list/winners"),
    "root/sales/act/stat/stat/list/poolprize": require("root/sales/act/stat/stat/list/poolprize"),
    "root/sales/act/stat/stat/list/userattend": require("root/sales/act/stat/stat/list/userattend"),
    "root/sales/eshop/coupon/list/setuse": require("root/sales/eshop/coupon/list/setuse"),
    "root/sales/eshop/coupon/list/lookDetail": require("root/sales/eshop/coupon/list/lookDetail"),
    "root/sales/act/stat/stat/list/lineCharts": require("root/sales/act/stat/stat/list/lineCharts"),
    "root/base/meta/channelList/setMoneyDialog": require("root/base/meta/channelList/setMoneyDialog"),
    "root/base/meta/channelList/recordDialog": require("root/base/meta/channelList/recordDialog"),
    "root/sales/act/act/act/list/export": require("root/sales/act/act/act/list/export"),
    "root/sales/eshop/adscategory/list/createDialog": require("root/sales/eshop/adscategory/list/createDialog"),
    "root/order/cardOrder/BenefitCardSnack/consumeOredr": require("root/order/cardOrder/BenefitCardSnack/consumeOredr"),
    "root/order/cardOrder/BenefitCardTicket/consumeOredr": require("root/order/cardOrder/BenefitCardTicket/consumeOredr"),
    "root/base/inApi/createDialog": require("root/base/inApi/createDialog"),
    "root/base/inApi/detailDialog": require("root/base/inApi/detailDialog"),
    "root/base/outApi/createDialog": require("root/base/outApi/createDialog"),
    "root/vip/manage/resetDialog": require("root/vip/manage/resetDialog"),
    "root/vip/manage/detailDialog": require("root/vip/manage/detailDialog"),
    "root/vip/manage/vipDialog": require("root/vip/manage/vipDialog"),
    "root/base/outApi/detailDialog": require("root/base/outApi/detailDialog"),
    "root/order/ticketCusOrder/orderDetailsDialog": require("root/order/ticketCusOrder/orderDetailsDialog"),
    "root/order/ticketAndSnackAduit/reviewDialog": require("root/order/ticketAndSnackAduit/reviewDialog"),
    "root/base/meta/cinemaLine/cinemaManageDialog": require("root/base/meta/cinemaLine/cinemaManageDialog"),
    "root/base/meta/cinemaLine/cinemaCreateDialog": require("root/base/meta/cinemaLine/cinemaCreateDialog"),
    "root/base/meta/cinemaLine/cinemaDetailDialog": require("root/base/meta/cinemaLine/cinemaDetailDialog"),
    "root/order/ticketCusOrder/statusDialog": require("root/order/ticketCusOrder/statusDialog"),
    "root/order/ticketCusOrder/historyDialog": require("root/order/ticketCusOrder/historyDialog"),
    'root/order/ticketCusOrder/refundDialog': require('root/order/ticketCusOrder/refundDialog'),
    "root/order/ticketCusOrder/applyNumberDialog": require("root/order/ticketCusOrder/applyNumberDialog"),
    "root/order/ticketAndSnackAduit/goodsDetailDialog": require("root/order/ticketAndSnackAduit/goodsDetailDialog"),
    'root/order/ticketCusOrder/sendTicketNODialog': require('root/order/ticketCusOrder/sendTicketNODialog'),
    'root/order/ticketCusOrder/queryStatusDialog': require('root/order/ticketCusOrder/queryStatusDialog'),
    "root/order/ticketAndSnackAduit/ticketDetailDialog": require("root/order/ticketAndSnackAduit/ticketDetailDialog"),
    "root/order/ticketAndSnackAduit/snackDetailDialog": require("root/order/ticketAndSnackAduit/snackDetailDialog"),
    "root/good/snak/cinemaSnack/selectCinemaDialog": require("root/good/snak/cinemaSnack/selectCinemaDialog"),
    "root/good/snak/snackType/addSnackDialog": require("root/good/snak/snackType/addSnackDialog"),
    "root/good/snak/snackList/setDateDialog": require("root/good/snak/snackList/setDateDialog"),
    "root/good/snak/cinemaSnack/modDateDialog": require("root/good/snak/cinemaSnack/modDateDialog"),
    "root/good/snak/cinemaSnack/setDateDialog": require("root/good/snak/cinemaSnack/setDateDialog"),
    "root/base/messageManage/messageTemplate/manage/createDialog": require("root/base/messageManage/messageTemplate/manage/createDialog"),
    "root/base/messageManage/templateType/manage/createDialog": require("root/base/messageManage/templateType/manage/createDialog"),
    "root/base/messageManage/messageTemplate/manage/viewDialog": require("root/base/messageManage/messageTemplate/manage/viewDialog"),
    "root/good/snak/snackList/confirmDialog": require("root/good/snak/snackList/confirmDialog"),
    "root/ghq/supplier/queryPagination/createDialog": require("root/ghq/supplier/queryPagination/createDialog"),
    "root/ghq/supplier/queryPagination/viewDialog": require("root/ghq/supplier/queryPagination/viewDialog"),
    "root/ghq/goodsCategory/queryPagination/create": require("root/ghq/goodsCategory/queryPagination/create"),
    "root/ghq/goodsCategory/queryPagination/lookDialog": require("root/ghq/goodsCategory/queryPagination/lookDialog"),
    "root/ghq/goods/queryPagination/viewDialog": require("root/ghq/goods/queryPagination/viewDialog"),
    "root/ghq/contract/queryPagination/addContract": require("root/ghq/contract/queryPagination/addContract"),
    "root/ghq/contract/queryPagination/viewContract": require("root/ghq/contract/queryPagination/viewContract"),
    "root/ghq/contract/queryPagination/addAllGood": require("root/ghq/contract/queryPagination/addAllGood"),
    "root/ghq/supplier/queryPagination/setGiftRule/addGood": require("root/ghq/supplier/queryPagination/setGiftRule/addGood"),
    "root/ghq/supplier/queryPagination/setGiftRule/addRule": require("root/ghq/supplier/queryPagination/setGiftRule/addRule"),
    "root/ghq/supplier/queryPagination/setGiftRule/viewRule": require("root/ghq/supplier/queryPagination/setGiftRule/viewRule"),
    "root/ghq/stl/queryPagination/chooseDialog": require("root/ghq/stl/queryPagination/chooseDialog"),
    "root/ghq/stl/queryPagination/chooseDetailDialog": require("root/ghq/stl/queryPagination/chooseDetailDialog"),
    "root/ghq/stl/queryPagination/lookDialog": require("root/ghq/stl/queryPagination/lookDialog"),
    "root/ghq/giftsOrder/queryPagination/viewDialog": require("root/ghq/giftsOrder/queryPagination/viewDialog"),
    "root/order/verification/ticket/detail/snackDetailsDialog": require("root/order/verification/ticket/detail/snackDetailsDialog"),
    "root/flow/def/configStep/createDialog": require("root/flow/def/configStep/createDialog"),
    "root/ghq/storageOrder/queryPagination/viewDialog": require("root/ghq/storageOrder/queryPagination/viewDialog"),
    "root/ghq/purchaseOrder/selectPurchaseOrder/viewDialog": require("root/ghq/purchaseOrder/selectPurchaseOrder/viewDialog"),
    "root/ghq/purchaseOrder/selectPurchaseOrder/createDialog": require("root/ghq/purchaseOrder/selectPurchaseOrder/createDialog"),
    "root/ghq/adjustPriceOrder/queryPagination/createDialog": require("root/ghq/adjustPriceOrder/queryPagination/createDialog"),
    "root/ghq/adjustPriceOrder/queryPagination/lookDialog": require("root/ghq/adjustPriceOrder/queryPagination/lookDialog"),
    "root/ghq/adjustPriceOrder/queryPagination/addGoodsDialog": require("root/ghq/adjustPriceOrder/queryPagination/addGoodsDialog"),
    "root/order/verification/voucher/validate/showCinemaDialog": require("root/order/verification/voucher/validate/showCinemaDialog"),
    "root/order/verification/voucher/validate/timeDialog": require("root/order/verification/voucher/validate/timeDialog"),
    "root/order/verification/voucher/validate/ruleDialog": require("root/order/verification/voucher/validate/ruleDialog"),
    "root/report/finance/v1/cinemaSettlement/selectCinemaDialog": require("root/report/finance/v1/cinemaSettlement/selectCinemaDialog"),
    "root/report/finance/v1/cinemaChannelSettlement/selectCinemaDialog": require("root/report/finance/v1/cinemaChannelSettlement/selectCinemaDialog"),
    "root/report/finance/v1/platChannelCinemaSettlement/selectCinemaDialog": require("root/report/finance/v1/platChannelCinemaSettlement/selectCinemaDialog"),
    "root/report/finance/v1/platBenCardDetail/selectCinemaDialog": require("root/report/finance/v1/platBenCardDetail/selectCinemaDialog"),
    "root/report/finance/v1/platChannelSettlement/selectCinemaDialog": require("root/report/finance/v1/platChannelSettlement/selectCinemaDialog"),
    "root/report/finance/v1/platConsumeSettlement/selectCinemaDialog": require("root/report/finance/v1/platConsumeSettlement/selectCinemaDialog"),
    "root/report/finance/v1/consumeSettlement/selectCinemaDialog": require("root/report/finance/v1/consumeSettlement/selectCinemaDialog"),
    "root/mhq/memberPolicy/search/addDialog": require("root/mhq/memberPolicy/search/addDialog"),
    "root/mhq/memberPolicy/search/editDialog": require("root/mhq/memberPolicy/search/editDialog"),
    "root/mhq/memberPolicy/search/syncToCinema": require("root/mhq/memberPolicy/search/syncToCinema"),
    "root/mhq/memberPolicy/search/lookLog": require("root/mhq/memberPolicy/search/lookLog"),
    "root/mhq/ngMemberPolicy/search/viewDialog": require("root/mhq/ngMemberPolicy/search/viewDialog"),
    "root/report/finance/v1/platSnackOrderDetail/selectCinemaDialog": require("root/report/finance/v1/platSnackOrderDetail/selectCinemaDialog"),
    "root/report/finance/v1/SnackOrderDetail/selectCinemaDialog": require("root/report/finance/v1/SnackOrderDetail/selectCinemaDialog"),
    "root/order/equityCardOrder/cardDialog": require("root/order/equityCardOrder/cardDialog"),
    "root/order/cinemaMemberAduit/orderDetailDialog": require("root/order/cinemaMemberAduit/orderDetailDialog"),
    "root/order/cinemaMemberAduit/checkDialog": require("root/order/cinemaMemberAduit/checkDialog"),
    "root/order/equityCardOrder/orderDialog": require("root/order/equityCardOrder/orderDialog"),
    "root/order/cinemaMemberOrder/refundDialog": require("root/order/cinemaMemberOrder/refundDialog"),
    "root/order/cinemaMemberOrder/orderDetailDialog": require("root/order/cinemaMemberOrder/orderDetailDialog"),
    "root/order/cinemaMemberOrder/fillDialog": require("root/order/cinemaMemberOrder/fillDialog"),
    "root/order/cinemaMemberOrder/fillLogDialog": require("root/order/cinemaMemberOrder/fillLogDialog"),
    "root/sales/eshop/comment/list/createDialog": require("root/sales/eshop/comment/list/createDialog"),
    "root/sales/eshop/comment/list/detailDialog": require("root/sales/eshop/comment/list/detailDialog"),
    "root/sales/eshop/sensitive/list/createDialog": require("root/sales/eshop/sensitive/list/createDialog"),
    "root/sales/eshop/sensitive/list/detailDialog": require("root/sales/eshop/sensitive/list/detailDialog"),
    "root/sales/eshop/appversion/list/createDialog": require("root/sales/eshop/appversion/list/createDialog"),
    "root/sales/eshop/app/list/createDialog": require("root/sales/eshop/app/list/createDialog"),
    "root/sales/eshop/paythird/list/createDialog": require("root/sales/eshop/paythird/list/createDialog"),
    "root/sales/eshop/paythird/list/detailDialog": require("root/sales/eshop/paythird/list/detailDialog"),
    "root/sales/eshop/paythird/list/pay": require("root/sales/eshop/paythird/list/pay"),
    "root/sales/mcard/cardset/list/createDialog": require("root/sales/mcard/cardset/list/createDialog"),
    "root/sales/eshop/paythird/list/look": require("root/sales/eshop/paythird/list/look"),
    "root/sales/eshop/suggest/list/mark": require("root/sales/eshop/suggest/list/mark"),
    "root/sales/eshop/suggest/list/reply": require("root/sales/eshop/suggest/list/reply"),
    "root/good/mcard/mfee/list/useCinemaDialog": require("root/good/mcard/mfee/list/useCinemaDialog"),
    "root/good/mcard/mfee/list/createDialog": require("root/good/mcard/mfee/list/createDialog"),
    "root/sales/eshop/minpricecinema/list/createDialog": require("root/sales/eshop/minpricecinema/list/createDialog"),
    "root/sales/eshop/minpricefilm/list/createDialog": require("root/sales/eshop/minpricefilm/list/createDialog"),
    "root/good/mcard/mprice/list/createDialog": require("root/good/mcard/mprice/list/createDialog"),
    "root/good/mcard/mprice/list/lookCinemaDialog": require("root/good/mcard/mprice/list/lookCinemaDialog"),
    "root/good/mcard/mprice/list/lookDetailDialog": require("root/good/mcard/mprice/list/lookDetailDialog"),
    "root/good/mcard/mprice/approvallist/lookCinemaDialog": require("root/good/mcard/mprice/approvallist/lookCinemaDialog"),
    "root/good/mcard/mprice/approvallist/lookDetailDialog": require("root/good/mcard/mprice/approvallist/lookDetailDialog"),
    "root/mmc/messageSetMenu/createDialog": require("root/mmc/messageSetMenu/createDialog"),
    "root/mmc/msgMenu/msgDetailDialog": require("root/mmc/msgMenu/msgDetailDialog"),
    "root/vip/mc/creditrule/list/createDialog": require("root/vip/mc/creditrule/list/createDialog"),
    "root/vip/mc/creditrule/cheklist/checkDialog": require("root/vip/mc/creditrule/cheklist/checkDialog"),
    "root/vip/mc/creditrule/list/detailDialog": require("root/vip/mc/creditrule/list/detailDialog"),
    "root/vip/mc/medallevel/list/createDialog": require("root/vip/mc/medallevel/list/createDialog"),
    "root/vip/mc/medallevel/list/manageDialog": require("root/vip/mc/medallevel/list/manageDialog"),
    "root/vip/mc/medalright/list/createDialog": require("root/vip/mc/medalright/list/createDialog"),
    "root/vip/mc/medalright/list/moveItemDialog": require("root/vip/mc/medalright/list/moveItemDialog"),
    "root/vip/mc/medalright/list/detailDialog": require("root/vip/mc/medalright/list/detailDialog"),
    "root/vip/mc/statistics/creditadd/dialog": require("root/vip/mc/statistics/creditadd/dialog"),
    "root/vip/mc/statistics/creditsub/dialog": require("root/vip/mc/statistics/creditsub/dialog"),
    "root/sales/eshop/suggestcategory/list/createDialog": require("root/sales/eshop/suggestcategory/list/createDialog"),
    "root/sales/eshop/faq/list/createDialog": require("root/sales/eshop/faq/list/createDialog"),
    "root/sales/eshop/faqcategory/list/createDialog": require("root/sales/eshop/faqcategory/list/createDialog"),
    "root/good/card/cardTypeManager/cardType/addLevel": require("root/good/card/cardTypeManager/cardType/addLevel"),
    "root/good/card/cardManager/applyDialog": require("root/good/card/cardManager/applyDialog"),
    "root/good/card/cardManager/explainDialog": require("root/good/card/cardManager/explainDialog"),
    "root/good/card/cardRuleApprove/snackRule/cardValue/lookDialog": require("root/good/card/cardRuleApprove/snackRule/cardValue/lookDialog"),
    "root/good/card/bigCustomer/productDialog": require("root/good/card/bigCustomer/productDialog"),
    "root/good/card/bigCustomer/lookDialog": require("root/good/card/bigCustomer/lookDialog"),
    "root/order/mcard/order/list/orderDetailDialog": require("root/order/mcard/order/list/orderDetailDialog"),
    "root/order/mcard/order/list/refundDialog": require("root/order/mcard/order/list/refundDialog"),
    "root/order/mcard/order/list/fillDialog": require("root/order/mcard/order/list/fillDialog"),
    "root/order/mcard/order/list/fillLogDialog": require("root/order/mcard/order/list/fillLogDialog"),
    "root/order/mcard/orderRefund/list/orderDetailDialog": require("root/order/mcard/orderRefund/list/orderDetailDialog"),
    "root/order/mcard/orderRefund/list/checkDialog": require("root/order/mcard/orderRefund/list/checkDialog"),
    "root/good/card/cardRuleApprove/ticketRule/cardValue/lookDialog": require("root/good/card/cardRuleApprove/ticketRule/cardValue/lookDialog"),
    "root/good/mcard/mprice/list/copyDialog": require("root/good/mcard/mprice/list/copyDialog"),
    "root/platform/otherRole/menu/selectCinemaDialog": require("root/platform/otherRole/menu/selectCinemaDialog"),
    "root/platform/otherRole/menu/viewDialog": require("root/platform/otherRole/menu/viewDialog"),
    "root/platform/otherRole/menu/createDialog": require("root/platform/otherRole/menu/createDialog"),
    "root/good/card/cardTypeManager/ticketRule/selectCinemaDialog": require("root/good/card/cardTypeManager/ticketRule/selectCinemaDialog"),
    "root/good/card/cardTypeManager/snackRule/selectCinemaDialog": require("root/good/card/cardTypeManager/snackRule/selectCinemaDialog"),
    "root/base/meta/cinemaList/mapDialog": require("root/base/meta/cinemaList/mapDialog"),
    "root/order/storedCardOrder/cardDialog": require("root/order/storedCardOrder/cardDialog"),
    "root/order/storedCardOrder/orderDialog": require("root/order/storedCardOrder/orderDialog"),
    "root/rmp/device/list/viewDialog": require("root/rmp/device/list/viewDialog"),
    "root/ghq/purchaseOrder/selectPurchaseOrder/addAllGood": require("root/ghq/purchaseOrder/selectPurchaseOrder/addAllGood"),
    "root/ghq/purchaseOrder/selectPurchaseOrder/createOrder": require("root/ghq/purchaseOrder/selectPurchaseOrder/createOrder"),
    "root/sales/eshop/paythird/list/order": require("root/sales/eshop/paythird/list/order"),
    "root/good/mcard/mprice/approvallist/returnDialog": require("root/good/mcard/mprice/approvallist/returnDialog"),
    "root/good/card/bigCustomer/batchDialog":require("root/good/card/bigCustomer/batchDialog"),
    "root/good/card/bigCustomer/selectCinemaDialog":require("root/good/card/bigCustomer/selectCinemaDialog"),
    "root/good/card/bigCustomer/lookCardDialog":require("root/good/card/bigCustomer/lookCardDialog"),
    "root/good/card/bigCustomer/exportDialog":require("root/good/card/bigCustomer/exportDialog"),
    "root/rmp/device/list/importDialog":require("root/rmp/device/list/importDialog"),
    "root/rmp/confManagement/all/createDialog": require("root/rmp/confManagement/all/createDialog"),
    "root/rmp/confManagement/all/lookDialog": require("root/rmp/confManagement/all/lookDialog"),
    "root/rmp/parts/all/createDialog": require("root/rmp/parts/all/createDialog"),
    "root/rmp/parts/all/editDialog": require("root/rmp/parts/all/editDialog"),
    "root/rmp/parts/all/msgDetailDialog": require("root/rmp/parts/all/msgDetailDialog"),
    "root/rmp/supplier/all/createDialog": require("root/rmp/supplier/all/createDialog"),
    "root/rmp/batchNumber/all/createDialog":require("root/rmp/batchNumber/all/createDialog"),
    "root/rmp/batchNumber/all/detailDialog": require("root/rmp/batchNumber/all/detailDialog"),
    "root/good/card/cardTypeManager/cardType/selectCinemaDialog":require("root/good/card/cardTypeManager/cardType/selectCinemaDialog"),
    "root/rmp/batchNumber/all/editDialog":require("root/rmp/batchNumber/all/editDialog"),
    "root/sales/eshop/ads/listnormal/createDialog":require("root/sales/eshop/ads/listnormal/createDialog"),
    "root/sales/eshop/ads/listnormal/chooseUrl": require("root/sales/eshop/ads/listnormal/chooseUrl"),
    "root/sales/eshop/ads/listnormal/order": require("root/sales/eshop/ads/listnormal/order"),
    "root/sales/eshop/ads/listapp/createDialog":require("root/sales/eshop/ads/listapp/createDialog"),
    "root/sales/eshop/ads/listmessage/createDialog":require("root/sales/eshop/ads/listmessage/createDialog"),
    "root/sales/eshop/ads/listmessage/addFilmDialog":require("root/sales/eshop/ads/listmessage/addFilmDialog"),
    "root/sales/eshop/ads/listtag/createDialog":require("root/sales/eshop/ads/listtag/createDialog"),
    "root/sales/eshop/ads/listact/createDialog":require("root/sales/eshop/ads/listact/createDialog"),
    "root/sales/eshop/ads/listnormal/viewDialog":require("root/sales/eshop/ads/listnormal/viewDialog"),
    "root/sales/naming/company/list/addDialog": require("root/sales/naming/company/list/addDialog"),
    "root/sales/naming/report/halllist/detailDialog": require("root/sales/naming/report/halllist/detailDialog"),
    "root/sales/naming/report/halllist/selectCinemaDialog": require("root/sales/naming/report/halllist/selectCinemaDialog"),
    "root/order/storedCardOrder/backDialog":require("root/order/storedCardOrder/backDialog")
};


var all_wait = [];

var that = {
    getDialog: function(id) {
        return modules[id];
    },
    getPop: function(id) {
        return modules[id];
    },
    /**
     * 弹出警告窗
     * @param  {[type]} text       显示的信息
     * @param  {[type]} onOkOrOpts 如果是函数，则是当点击确定的时候的回调。如果是对象，则是配置信息
     * @return {[type]}            弹层对象
     */
    alert: function(text, onOkOrOpts) {
        var opts = null;

        if (typeof onOkOrOpts == "function") {
            opts = {
                "ok": onOkOrOpts
            }
        } else {
            opts = onOkOrOpts;
        }

        var dialog = that.getDialog("plugin/dialog/alert");
        var m_dialog = dialog(text, opts);
        m_dialog.show();

        return m_dialog;
    },
    /**
     * 弹出警告窗
     * @param  {[type]} text       显示的信息
     * @param  {[type]} onOkOrOpts 如果是函数，则是当点击确定的时候的回调。如果是对象，则是配置信息
     * @param  {[type]} onCancel   如果onOKOrOpts是函数，则允许这里传入函数作为点击取消时的回调，如果onOKOrOpts为对象，则该参数失效
     * @return {[type]}            弹层对象
     */
    confirm: function(text, onOkOrOpts, onCancel) {
        var opts = null;

        if (typeof onOkOrOpts == "function" && typeof onCancel == "function") {
            opts = {
                "ok": onOkOrOpts,
                "cancel": onCancel
            }
        } else if (typeof onOkOrOpts == "function") {
            opts = {
                "ok": onOkOrOpts
            }
        } else {
            opts = onOkOrOpts;
        }

        var dialog = that.getDialog("plugin/dialog/confirm");
        var m_dialog = dialog(text, opts);
        m_dialog.show();

        return m_dialog;
    },
    /**
     * 弹出等待加载
     * */
    wait: function() {
        var dialog = that.getDialog("plugin/dialog/wait");
        var m_dialog = dialog();
        m_dialog.show();
        all_wait.push(m_dialog);
    },
    /**
     * 关闭等待加载
     * */
    closeWait: function() {
        all_wait.forEach(function(item) {
            item.hide();
        });
        all_wait = [];
    },
    toast: function(str) {
        var dialog = that.getDialog("plugin/dialog/toast");
        var m_toast = dialog(str);
        m_toast.show();
    }
};

module.exports = that;
window.dialogManager = that;